version: '3'
services:
  kestra:
    image: kestra/kestra:latest
    environment:
      - KESTRA_SERVER_HOST=0.0.0.0
      - KESTRA_SERVER_PORT=8080
    volumes:
      - ./kestra:/kestra  # Mount the kestra directory to the container
    ports:
      - "8080:8080"  # Expose the Kestra UI on port 8080
